# Generated by Django 5.1.6 on 2025-02-18 14:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("speaker", "0002_alter_speaker_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=5000)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("speakers", models.ManyToManyField(to="speaker.speaker")),
            ],
        ),
    ]
